export const articles = [
    {
        path: 'github-actions-iam-roles',
        picture_path: 'blog/github-actions-iam-roles.gif',
        title: 'Configuring GitHub Actions with OIDC and IAM Roles',
        categories: ['identity'],
        tags: ['aws', 'aim', 'security', 'permissions', 'roles', 'policies', 'github-actions', 'integration', 'oidc'],
        publication_date: '2025-04-29',
        visits: 385,
    },
    {
        path: 'native-iac-tools',
        picture_path: 'blog/native-iac-tools.png',
        title: 'Native IaC Tools on AWS: CloudFormation and CDK',
        categories: ['iac'],
        tags: ['aws', 'cloudformation', 'cdk', 'iac', 'automation'],
        publication_date: '2025-01-02',
        visits: 785,
    },{
        path: 'dynamodb-overview',
        picture_path: 'blog/dynamodb-overview.png',
        title: 'All You Need to Know About Amazon DynamoDB',
        categories: ['serverless'],
        tags: ['aws', 'dynamodb', 'nosql', 'database', 'serverless', 'scalability', 'performance'],
        publication_date: '2024-06-13',
        visits: 216,
    },
    {
        path: 'cloud-computing-introduction',
        picture_path: 'blog/cloud-computing-introduction.webp',
        title: 'Unlocking cloud mastery: an introductory course to Cloud Computing',
        categories: ['introduction'],
        tags: ['aws', 'intro'],
        publication_date: '2023-10-21',
        visits: 542,
    },
    {
        path: 'ec2-introduction',
        picture_path: 'blog/ec2-introduction.webp',
        title: 'Discovering EC2: Your Gateway to Cloud Computing with AWS',
        categories: ['compute'],
        tags: ['aws', 'ec2', 'iaas', 'linux', 'security-groups', 'ssh', 'access-keys', 'vpc'],
        publication_date: '2023-11-09',
        visits: 940,
    },
    {
        path: 'iam-introduction',
        picture_path: 'blog/iam-introduction.png',
        title: 'Managing Secure Access to AWS with Identity and Access Management (IAM)',
        categories: ['identity'],
        tags: ['aws', 'iam', 'security', 'permissions', 'roles', 'policies', 'users', 'groups'],
        publication_date: '2023-11-10',
        visits: 330,
    },
    {
        path: 'learning-resources',
        picture_path: 'blog/learning-resources.webp',
        title: 'Empowering Your Cloud Journey: A Curated List of Resources to Master AWS',
        categories: ['introduction'],
        tags: ['aws', 'intro', 'resources', 'courses', 'books', 'tutorials'],
        publication_date: '2023-10-29',
        visits: 225,
    },
    {
        path: 'aws-overview',
        picture_path: 'blog/aws-overview.webp',
        title: 'AWS Overview',
        categories: ['introduction'],
        tags: ['aws', 'intro'],
        publication_date: '2023-10-22',
        visits: 225,
    },
];